Add MANIFEST.in
magmax/python-inquirer pull request #120
Opened 2021-09-15 18:22 UTC by SteinRobert

Adds MANIFEST.in. Closes #106 

With the MANIFEST.in added the requirements.txt is also included in the tarball. 
I encountered this issue as I was using `inquirer` as a dependency for a python cli tool. Installing the tool via `brew` on OSX fails, since it depends on a correctly packaged tarball for all dependencies.

2021-09-15 18:23 UTC, SteinRobert commented
@AuHau any chance you could take a look at this?

2021-11-18 19:06 UTC, staticdev requested changes
I actually find this an old style solution for the problem. As mentioned in #106 I would solve creating a pyproject.toml, making it compliant with new PEPs 517/518.

2021-11-18 19:24 UTC, SteinRobert commented
Thank you for your feedback. We moved on to https://github.com/kazhala/InquirerPy since provides us with some features we had been missing in python-inquirer. I guess you should not wait for me updating the PR. 
Than you so much for your support!

2021-11-18 19:32 UTC, staticdev commented
Ok @SteinRobert, thanks for the heads-up. I will try to do some updates here. Also will check out the project.

2021-11-18 20:06 UTC, staticdev commented
Also @SteinRobert you mentioned features you needed. Something in particular missing here you use?

2021-11-18 20:18 UTC, SteinRobert commented
@staticdev we're making heavy use of the [fuzzy prompt](https://inquirerpy.readthedocs.io/en/latest/pages/prompts/fuzzy.html). 
The particular project we're working on is a cli: https://github.com/unikubehq/cli (obviously :) ) 
The thing is - we're creating a homebrew formula to make the cli installable on OSX. This usually works through installing tar.gz files of all dependencies (like the inquirer package). Since the requirements.txt is missing from the tarball of this package it is basically not installable and broke our OSX installation process. That's the reason we started looking for alternatives and moved on to InquirerPy.

2021-11-18 20:29 UTC, staticdev commented
Very interesting feature indeed! I also have some CLIs I work on, mostly on https://github.com/staticdev/git-portfolio (project to help manage more projects on Github/git)

2021-12-12 13:51 UTC, staticdev commented
Decided to reopen in favor to https://github.com/magmax/python-inquirer/pull/134

pyproject.toml will wait for longer.

2021-12-12 13:52 UTC, merged