Fix for Python3.10
magmax/python-inquirer pull request #123
Opened 2021-10-25 23:50 UTC by ZhymabekRoman

Hello, I fixed the problem that appears in Python 3.10. The problem was specifically in the library blessed, or rather it did not correctly determine the version of Python, and caused an exception - https://github.com/jquast/blessed/commit/9fd1f6f1322c3691f70ed3036b68c5eebacdb428#diff-ef31c42ff551912ac1c50d3bdbe64043fa7b470854e682c8e0975a874516a8d9. This issue has been fixed in blessed 1.17.9

I also removed the try except block in the __ init __ .py file because I see no meaning in it. When I first ran the script with the inquirer in Python 3.10, he told me 'module' inquirer 'has no attribute' List, "I didn't understand what the problem was, but it turns out he typed a regular message that says Blessed Python 3.2.3 or higher is needed, although I generally have Python 3.10 worth.

2021-11-02 00:12 UTC, ZhymabekRoman commented on inquirer/__init__.py
> -try:
I don't understand why to hide an exception from a person. If there is any problem during the import, then let an exception be caused, and not just a regular message. I myself did not personally understand the first time why he tells me, 
```AttributeError: module 'inquirer' has no attribute 'List'```
it turns out that just the usual message about the problem with the blessed library was displayed a little higher.

I found a commit that adds the change itself, but I still do not understand the point of this change, it is more of a workaround than a full-fledged solution to the problem -https://github.com/magmax/python-inquirer/commit/26ba987644282e295fd2e83429e022f5003a4895

2021-11-03 21:14 UTC, xFGhoul commented on inquirer/__init__.py
> -try:
Then this should be a seperate PR instead of bundling it into this one

2021-11-18 18:58 UTC, staticdev requested changes
@ZhymabekRoman thanks for your PR. Please add to python-inquirer/.github/workflows/python-test.yml tests for Python 3.10.

2021-11-19 00:45 UTC, ZhymabekRoman commented
> @ZhymabekRoman thanks for your PR. Please add to python-inquirer/.github/workflows/python-test.yml tests for Python 3.10. If possible also the classifier for Python 3.10 on setup.py.

@staticdev, thanks, done!

2021-11-19 09:49 UTC, staticdev commented
@ZhymabekRoman I will review/merge/release ASAP (most probably later today or max tomorrow).

2021-11-19 11:40 UTC, staticdev approved these changes
All good.

2021-11-19 11:41 UTC, merged

2021-11-19 12:06 UTC, staticdev commented
@ZhymabekRoman it is now on PyPI version 2.8.0. You can give it a try.