Update README.rst
magmax/python-inquirer pull request #133
Opened 2021-12-12 00:43 UTC by zxyle

Supplemental installation information

2021-12-12 13:46 UTC, staticdev requested changes
Thanks for your PRs, could you please take a look at a comment I made?

2021-12-12 13:46 UTC, staticdev commented on README.rst
> +.. code:: bash
Please change to:
.. code:: console

So that syntax highlighting works better.

2021-12-13 02:15 UTC, zxyle commented
I have modified again, please merge this PR

2021-12-13 08:08 UTC, staticdev approved these changes

2021-12-14 17:18 UTC, merged