Move the import of python-editor into the scope where it is actually needed
magmax/python-inquirer pull request #151
Opened 2022-01-20 23:55 UTC by philipbergen

Move the import of python-editor into the scope where it is actually needed, so that inquirer can mostly function on default ubuntu python. See comment in code.

2022-01-20 23:56 UTC, philipbergen commented
Let me know if you need some version bumps or something.

2022-01-21 06:07 UTC, staticdev requested changes

2022-01-21 06:07 UTC, staticdev commented on pyproject.toml
>  description = "Collection of common interactive command line user interfaces, based on Inquirer.js"
Please remove this. Is not necessary for PR.

2022-01-21 06:07 UTC, staticdev commented on src/inquirer/render/console/_editor.py
>              data = editor.edit(contents=self.question.default or "")
Could you please provide a test for CI/CD that would not work if the import is in its original place?

2022-01-21 06:11 UTC, staticdev commented
@philipbergen thanks for your PR. I made some comments on your code and also noticed you did not run pre-commit before commiting (more instructions [here](https://github.com/magmax/python-inquirer/blob/master/CONTRIBUTING.rst)).

2022-01-24 18:44 UTC, philipbergen commented
I ran `nox --session=pre-commit -- install` and it passes after I installed py3.10 on my system, but no files were updated. Not sure if I did that right.

2022-01-24 18:59 UTC, philipbergen commented
You asked for a test, I looked at tests.yml and I can't really figure out how to add a test like:
```
steps:
  - name: Check with plain ubuntu python (without python3-distutils)
     uses: {os: ubuntu-latest}
     run: |
       echo 'import inquirer' | python3
```

The important part here is to test on a plain ubuntu, without any magic installing python and particularly the `python3-distutils` package.

2022-11-21 05:22 UTC, staticdev commented
Close for lack of response.

2022-11-21 05:22 UTC, closed without merging