bump readchar required version
magmax/python-inquirer pull request #206
Opened 2022-07-27 14:05 UTC by Cube707

readchars v3.0.5 broke linux support and will be avoided by this. Additionally the newer versions fix windows support for arrow-keys

fixes #198, closes #156, closes #155

2022-07-27 17:53 UTC, staticdev requested changes
@Cube707 thanks for the update. Please, now that you changed `pyproject.toml` you need to execute `poetry lock` and also commit `poetry.lock`.

2022-07-27 18:45 UTC, Cube707 commented
@staticdev sorry I never worked with poetry and didn't know that. Should be done now, even if github isn't picking it up.

2022-07-28 11:37 UTC, Cube707 commented
I also just realsied that it might be a usefull step to limit the readchar version, as `v4.0.0` is currently in pre-release and intreduces some big changes.

2022-07-28 16:40 UTC, staticdev commented
> I also just realsied that it might be a usefull step to limit the readchar version, as `v4.0.0` is currently in pre-release and intreduces some big changes.

For now I think it is ok, since latest release is 3.1.0. If we know the code will break when 4.0.0 is released than we change something.

2022-07-28 16:41 UTC, staticdev approved these changes
LGTM.

2022-07-28 16:43 UTC, merged