doc-build requires python 3.9?
magmax/python-inquirer pull request #226
Opened 2022-08-10 14:12 UTC by Cube707

I have failures in the documaentation workflow over on my fork: ([see herer](https://github.com/Cube707/python-inquirer/runs/7768246980?check_suite_focus=true)). I assue it is because the `docs-build`sesstion is pint to python 3.9?? See:

https://github.com/magmax/python-inquirer/blob/1cd386f1af4d677c5babca950fcd4af0f23c2c0d/noxfile.py#L190-L191

I changed the workflow to also use python 3.9 and it seems to fix the issue. Is this senesible or am I overlooking something?

2022-08-10 17:28 UTC, staticdev commented
@Cube707 this is strange, I have 3.10 already in all my repos and it is working fine. Eg: https://github.com/staticdev/irpf-investidor/blob/main/noxfile.py

2022-08-10 17:35 UTC, staticdev requested changes
Can you try instead changing noxfile to use 3.10 with:

```python
@session(name="docs-build", python=python_versions[0])
```

2022-08-10 18:36 UTC, Cube707 commented
> Can you try instead changing noxfile to use 3.10

I hoped this would be a windows issue, but both my windows machine and the github CI throw an error: ([see here](https://github.com/magmax/python-inquirer/runs/7772946127?check_suite_focus=true))

```
Extension error:
Could not import extension sphinx.builders.linkcheck (exception: cannot import name 'Mapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/collections/__init__.py))
nox > Command sphinx-build -b linkcheck -W --keep-going docs docs/_build failed with exit code 2
nox > Session docs-build failed.
``` 

It seems to be a problem with an old version of requests? But it should pull the latest version shoudn't it??

2022-08-10 19:14 UTC, Cube707 commented
looks like it is a configuration issue. This sucseeds:

```bash
python -m venv .venv
.venv\Scripts\activate
pip install -e .
pip install sphinx furo
sphinx-build --color docs docs/_build
```

2022-08-10 20:23 UTC, staticdev commented
> > Can you try instead changing noxfile to use 3.10
> 
> I hoped this would be a windows issue, but both my windows machine and the github CI throw an error: ([see here](https://github.com/magmax/python-inquirer/runs/7772946127?check_suite_focus=true))
> 
> ```
> Extension error:
> Could not import extension sphinx.builders.linkcheck (exception: cannot import name 'Mapping' from 'collections' (/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/collections/__init__.py))
> nox > Command sphinx-build -b linkcheck -W --keep-going docs docs/_build failed with exit code 2
> nox > Session docs-build failed.
> ```
> 
> It seems to be a problem with an old version of requests? But it should pull the latest version shoudn't it??

You know.. i would just remove this links check from sphinx on nox. It is very buggy and not effective.. maybe in the future they will fix it.

2022-08-10 20:28 UTC, Cube707 commented
I just found something posible related: 

> sphinx (>4.3.2) requires importlib-metadata (>=4.4).
> And because flake8 (>=4.0.1) requires importlib-metadata (<4.3) (1), flake8 (>=4.0.1) is incompatible with sphinx (>4.3.2)
> So, because inquirer depends on both sphinx (>4.3.2) and flake8 (>=4.0.1), version solving failed.

But only the newer spinx version (I used 5.1.1) work on my system, so this may be the cause.

2022-08-10 21:24 UTC, Cube707 commented
I went through the logs of the action runs and also tested with older versions, looks like this never worked...

2022-08-10 21:32 UTC, Cube707 commented
I experimented around but I cant't find a soloution. Your other repos works just fine on my system so it's defnetly a config problem here.

Also I couldn't figure out how to disable the linkchecker. Just removing the arguments from the call to `sphinx-build` still raised the issue from `sphinx.builders.linkcheck` 😒 

At least I found out how to get `sphinx` to update, it requires `python >= 3.8`

2022-08-10 21:34 UTC, Cube707 commented
In my opinion, as pinning it to run on python 3.9 has no relevant drawbacks and is a simple fix, I would proably just keep the original commit

2022-08-11 14:27 UTC, Cube707 commented
soooo, I found the soloution: This stems from the `urllib3` libary having changed its version classifyers at some point. Older versions only hat a lower bound on the required python version, but at some point they also added `python>4` into the requirement. This clashes with our declaration of only a lower bound and therfore only installes super old versions of `urllib3` that don't work with python 3.10.

To solve this we need to pin some part of our dependency tree to `python>4`, in the current test-commit I only pinned verything under `sphinx`, but maybe it makes more sense to pin our full package? What do you think @staticdev

2022-08-11 17:48 UTC, staticdev commented
@Cube707 **in general** pinning versions on `pyproject.toml` is not recommended, this is basically one of the reasons why we also have `poetry.lock`. Having that said, not all packages follow the rule leading sometimes to problems like that one you discovered. I think we are following the best practice and we should restrict our dependencies as little as possible and this will help ensure that python-inquirer will be compatible with future versions of other dependencies.

BTW there is a great article explaining reasoning more in depth here: https://iscinumpy.dev/post/bound-version-constraints/ (see the section titled Pinning the Python version is special)

2022-08-11 18:06 UTC, Cube707 commented
OK, thats what i figured. Than lets keep it like it is and only change `sphinx` ad its dependencies via:

```toml
sphinx = {version=">=4.3.2", python="<4"}
```

2022-08-11 18:07 UTC, Cube707 commented
> BTW there is a great article explaining reasoning more in depth here: https://iscinumpy.dev/post/bound-version-constraints/

I found that exact article already when researching this, it's very informative

2022-08-11 18:13 UTC, staticdev approved these changes

2022-08-11 18:18 UTC, merged