Add "Other..." option for checkbox & list questions
magmax/python-inquirer pull request #256
Opened 2022-10-03 14:38 UTC by WilliamVenner

This PR adds a feature to checkbox and list questions which allows users to enter custom input.

https://user-images.githubusercontent.com/14863743/193604405-effc7732-6c69-4e16-9fe0-2ebf7d582f79.mov

2022-10-07 07:14 UTC, Cube707 commented
I like the idea and it makes sense as an opt-in feature so that developters an enable it where needed. I will review the code later...

I would argue that its better placed as the last element in the list rather than the first thought. Makes more sense to me.

2022-11-07 09:13 UTC, cpiemontese commented
A little bump to know if this has been reviewed yet :pray:

2022-11-09 17:44 UTC, Cube707 commented on src/inquirer/questions.py
> +            choices.append(GLOBAL_OTHER_CHOICE)
this is a little redudent, move the `if` doen and append directly to `self._choises`, no need for the additional `or []`

2022-11-09 17:45 UTC, Cube707 commented on src/inquirer/questions.py
> +        self._other = other
I would find it more logical, if they would match the order in which they are passed to the function, so maybe move it down?

2022-11-09 17:56 UTC, Cube707 requested changes
made some small comments.

And the tests fail, I don'T have the time to check why at the moment though, maybe you can figure it out quicker than i can

2022-11-09 19:14 UTC, staticdev requested changes
Last commit broke the tests. I pointed in comment why.

2022-11-09 19:14 UTC, staticdev commented on tests/acceptance/test_checkbox.py
> +        self.sut.expect(r"> X Hello world[\s\S]*\+ Other\.\.\..*", timeout=1)
the tests are still checking it there are ... aftrr Other. This is why it is failing.

2022-11-10 11:10 UTC, WilliamVenner commented
Cheers all, have made the requested changes. Sorry if the tests still don't pass, I would run them locally but it's a bit of a PITA due to M1 chip. Fingers crossed 🤞🏻

2022-11-10 13:21 UTC, Cube707 approved these changes

2022-11-11 15:57 UTC, merged