add list and checklist length parameter
magmax/python-inquirer pull request #81
Opened 2020-01-27 16:15 UTC by tmsteen

I added some functionality to address #80 

I tested with a script I was using and it seems to work effectively.  I do not have any idea what the side effects to this change might be. 

The biggest change was moving `MAX_OPTIONS_DISPLAYED_AT_ONCE` inside `BaseConsoleRender` so that it could be used as an instance variable. 

I did not do any style updates, so if that is desired I can try to do that in a different commit. 

Current things I did not have time to address:
* Validating length to ensure it is an int
* Functionality to determine if the selected length is longer than the terminal window itself.

2020-01-29 13:46 UTC, tmsteen commented
I did just notice that there is a problem with this when you get to the bottom of the list and it does not scroll anymore...the selector is off by one (selects the line above) and you cannot select the last item, will have to look into that.

2020-01-30 13:47 UTC, tmsteen commented
Per the comment with how the length was set originally, selecting an even number length will have this issue.  An odd number length has not issues. 

`# Should be odd number as there is always one question selected`

2020-01-30 14:07 UTC, tmsteen commented
Latest commit fixes the even/odd issue.

2021-11-18 19:18 UTC, staticdev requested changes
@tmsteen Thanks for your PR. Could you rebase it with latest code?

2021-12-27 18:34 UTC, staticdev commented
Closing since user @tmsteen does not respond and seem active.

2021-12-27 18:34 UTC, closed without merging